version: '3'
services:
  frontend:
    build: ./frontend
    # Node.jsのグローバル変数です。開発用途なのでdevelopmentを指定します。
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/frontend
    command: sh -c 'yarn install && yarn dev'
    ports:
      - 3000:3000
    tty: true
